In [1]:
import pandas as pd
import numpy as np

# Bag of Words

In [6]:
df = pd.DataFrame({"text":["people watch Youtube",
                         "Asit watch youtube",
                         "people write comment",
                          "Asit write comment"],"output":[1,1,0,0]})

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [10]:
bow = cv.fit_transform(df['text'])

In [12]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'youtube': 5, 'asit': 0, 'write': 4, 'comment': 1}


In [16]:
bow.toarray()

array([[0, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 0, 1],
       [0, 1, 1, 0, 1, 0],
       [1, 1, 0, 0, 1, 0]], dtype=int64)

In [18]:
# new
cv.transform(['Bappy watch youtube']).toarray()

array([[0, 0, 0, 1, 0, 1]], dtype=int64)

In [20]:
X = bow.toarray()
y = df['output']

## N Grams

In [28]:
df = pd.DataFrame({"text":["people watch Youtube",
                         "Asit watch youtube",
                         "people write comment",
                          "Asit write comment"],"output":[1,1,0,0]})

In [30]:
df

text  output
0  people watch Youtube       1
1    Asit watch youtube       1
2  people write comment       0
3    Asit write comment       0

In [32]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [34]:
bow = cv.fit_transform(df['text'])

In [36]:
print(cv.vocabulary_)

{'people watch': 2, 'watch youtube': 4, 'asit watch': 0, 'people write': 3, 'write comment': 5, 'asit write': 1}


In [38]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


In [40]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [42]:
bow = cv.fit_transform(df['text'])

In [46]:
print(cv.vocabulary_)

{'people watch youtube': 2, 'asit watch youtube': 0, 'people write comment': 3, 'asit write comment': 1}


In [48]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]
